### PR TITLE
Cross-platform slip-radio example

### PR DESCRIPTION
**Pull request by g-oikonomou**
This pull applies a number of changes to slip radio example. This pull:

* Changes to example to use early target identification from #122 and, based on that, allows platform-specific extensions/configuration
* Moves sky-specific extensions/configuration to a subdir. Some limiting configuration defines now only apply to sky builds (e.g. limiting the uIP buffer size). Some extensions (e.g. custom commands) are built conditionally.
* Removes some code artifacts that have to do with legacy radios/platforms (e.g. mc13xx)
* Changes some functions to static
* Changes the example to use the logging module
* Adds some compile tests for the example to travis
* Fixes code style

Sits on top of #131, requires #122

### CODE REVIEW

**Comment by simonduq** [comment]
👍

**Comment by joakimeriksson** [comment]
Looks great! 👍

**Comment by g-oikonomou** [comment]
Rebased on top of #131, but other than that all good to merge here.

**Comment by g-oikonomou** [comment]
Rebased

**Comment by g-oikonomou** [comment]
Travis happy. Merging

**Pull request merged**
