### PR TITLE
Cooja: use $(MAKE) in simulation files

### PR DESCRIPTION
**Pull request by pjonsson**
This will expand to the make configured either by the user or the make configured for the platform.

### CODE REVIEW

**Review by nfi — APPROVED** [review]

**Comment by nvt** [comment]
From what I recall, we have not had this dependency on MAKE being set before, and I do not see it mentioned in the documentation. If it is not set, we will with this change get this type of error:

org.contikios.cooja.MoteType$MoteTypeCreationException: Compilation error: Cannot run program "$(MAKE)" (in directory "/home/nvt/contiki-ng/examples/rpl-udp"): error=2, No such file or directory

**Comment by pjonsson** [comment]
> From what I recall, we have not had this dependency on MAKE being set before, and I do not see it mentioned in the documentation. If it is not set, we will with this change get this type of error:
> 
> org.contikios.cooja.MoteType$MoteTypeCreationException: Compilation error: Cannot run program "$(MAKE)" (in directory "/home/nvt/contiki-ng/examples/rpl-udp"): error=2, No such file or directory

Is that macOS or Linux? What does PATH_MAKE in Setings->External tools paths show for you?

**Comment by nvt** [comment]
Ubuntu Linux 23.04, native toolchain installation.

PATH_MAKE=make in Settings->External tools

**Comment by pjonsson** [comment]
It is Cooja that should do the expansion, does `git submodule update` make the problem disappear?

**Comment by nvt** [comment]
Thanks, the example builds now with the updated submodule.

**Pull request merged**
