### PR TITLE
add '\0' terminal character

### PR DESCRIPTION
**Pull request by Rehan-MALAK**
(these commits do not remove the new gcc-8 "stringop-truncation" warnings as in the previous #620 suggestion)

### CODE REVIEW

**Comment by Rehan-MALAK** [comment]
I also noticed recently that the particular section concerned by the patch in example/examples/rpl-border-router/webserver/httpd-simple.c  do not seem reached by one of the tests in tests/17-tun-rpl-br/ .

Would be nice if @nfi could confirm that I didn't screw up his code.

**Comment by g-oikonomou** [comment]
Requires minor code style fixes please

**Comment by Rehan-MALAK** [comment]
''tab[index-1] = 0;'' => ''tab[index - 1] = 0;''

but havn't been able to use unscrutiny. #655

**Comment by simonduq** [comment]
@g-oikonomou waiting for your approval here now :)

**Pull request merged**
