### PR TITLE
TSCH: filter out frames from ourselves

### LINKED ISSUE #748: TSCH: discard frames from ourselves
Like https://github.com/contiki-ng/contiki-ng/pull/743 does for CSMA

### PR DESCRIPTION
**Pull request by simonduq**
Resolves #748

### CODE REVIEW

**Comment by simonduq** [comment]
@yatch any clue what might go wrong with the test here? Maybe somewhere there is an assumption that we can receive from our own address?

**Comment by yatch** [comment]
@simonduq I will take a look.

**Comment by yatch** [comment]
Interesting :-)

```
Running test 01-panid-handling with random Seed 1........ OK
Running test 02-tsch-flush-nbr-queue with random Seed 1....... OK
Running test 03-cooja-test-sixtop with random Seed 1........ OK
Running test 04-cooja-test-sixp-pkt with random Seed 1........./../tests/simexec.sh: line 67:  3239 Aborted                 (core dumped) java -Xshare:on -jar 
...
==== 04-cooja-test-sixp-pkt.1.scriptlog ====
Random seed: 1
549000 node-1 [INFO: Main      ] - Routing: RPL Lite
549000 node-1 [INFO: Main      ] - Net: sicslowpan
...
678000 node-1 =check-me= SUCCEEDED - test sixp_pkt_create(too_long_body)
679000 node-1 =check-me= DONE
TEST OK
Running test 05-cooja-test-sixp-trans with random Seed 1........ OK
Running test 06-cooja-test-sixp-nbr with random Seed 1....... OK
Running test 07-cooja-test-sixp with random Seed 1........ OK
```

The failed test, `04-cooja-test-sixp-pkt`, actually succeeded. You can see "TEST OK" in the log. But, Travis says a null pointer access happened somehow and somewhere.

The whole test succeeds on my local machine:
```
$ contiker make -C tests/13-ieee802154
make: Entering directory '/home/user/contiki-ng/tests/13-ieee802154'
Running test 01-panid-handling with random Seed 1................. OK
Running test 02-tsch-flush-nbr-queue with random Seed 1.................. OK
Running test 03-cooja-test-sixtop with random Seed 1................. OK
Running test 04-cooja-test-sixp-pkt with random Seed 1.................. OK
Running test 05-cooja-test-sixp-trans with random Seed 1................... OK
Running test 06-cooja-test-sixp-nbr with random Seed 1.................. OK
Running test 07-cooja-test-sixp with random Seed 1................... OK
========== Summary ==========
01-panid-handling                        TEST OK      1/1
02-tsch-flush-nbr-queue                  TEST OK      1/1
03-cooja-test-sixtop                     TEST OK      1/1
04-cooja-test-sixp-pkt                   TEST OK      1/1
05-cooja-test-sixp-trans                 TEST OK      1/1
06-cooja-test-sixp-nbr                   TEST OK      1/1
07-cooja-test-sixp                       TEST OK      1/1
make: Leaving directory '/home/user/contiki-ng/tests/13-ieee802154'
$ git show HEAD --oneline -s
4cc64ea94 (HEAD) TSCH: filter out frames from ourselves
```

I will re-run the test.

**Comment by simonduq** [comment]
OK, some randomness involved :s I wonder if this PR makes anything more flaky for some reason... I'll rerun it a few times and see this occurs again. Thanks!

**Comment by simonduq** [comment]
Tested multiple times and did not fail again

**Pull request merged**
