### PR TITLE
Substitute the npm coap client for the one in libcoap

### PR DESCRIPTION
**Pull request by g-oikonomou**
libcoap is a more mature coap implementation so we remove the old npm client (`coap-cli`) in favour of the one provided with libcoap (`coap-client`).

Unfortunately a package with binaries is not provided for Ubuntu 16.04, so we have to compile from sources. We only need to do this when rebuilding the docker image.

This PR also opportunistically moves `native-ping` and `native-coap` tests from the `tun-rpl-br` travis task to the `native-runs` one.

Suggest including in 4.4 unless objections

### CODE REVIEW

**Comment by g-oikonomou** [comment]
Draft for now: I have removed some stuff to make travis builds quicker for testing

**Comment by g-oikonomou** [comment]
Also changed our vagrant bootstrapping script and ready for review

**Comment by alexandruioanp** [comment]
If #1115 is merged, this can be installed as a package.

**Comment by g-oikonomou** [comment]
I have reworked this PR.

We now install libcoap as a package instead of compiling from sources. We apply this change to both our docker container as well as our vagrant image.

#1069, also applies to the vagrant image. This PR fixes the situation.

Requires #1140 but otherwise ready for review, so I am removing the wip label

**Pull request merged**
