### PR TITLE
Fix use of srcipaddr.

### PR DESCRIPTION
**Pull request by jeandudey**
Signed-off-by: Jean Pierre Dudey <jeandudey@hotmail.com>

### CODE REVIEW

**Comment by yatch** [comment]
`ripaddr` has the remote IPv6 address of the connection. That's why it is compared with the source IPv6 address of the received packet. The code is aligned with the comment found above.

```
   1529     /* If the local UDP port is non-zero, the connection is considered
               ...
   1533        connection is bound to a remote port. Finally, if the
   1534        connection is bound to a remote IP address, the source IP
   1535        address of the packet is checked. */
   1536     if(uip_udp_conn->lport != 0 &&
               ...
   1541         uip_ipaddr_cmp(&UIP_IP_BUF->srcipaddr, &uip_udp_conn->ripaddr))) {
   1542       goto udp_found;
```

**Comment by jeandudey** [comment]
@yatch How sould one receive a packet that sent through a to a broadcast address (`ff02::1`) then?

**Comment by yatch** [comment]
1.  join a multicast group using `uip_ds6_maddr_add()`
1. open a UDP socket, and bind it to a port

That's all.

Since `ff02::1` is automatically registered at startup, you can skip the first step for this address. If you set the log level of IPv6 to DBG, you will see logs like this on reception of a multicast UDP packet:

```
[INFO: IPv6      ] packet received from fe80::4843:4947:4aad:a326 to ff02::1
[INFO: IPv6      ] Receiving UDP packet
[DBG : IPv6      ] Upper layer checksum len: 12 from: 40
[DBG : IPv6      ] In udp_found
```

If you use `simple_udp_register()` to set up an UDP socket, check the remote port for the function is identical to the source port number of multicast UDP packets.

**Comment by yatch** [comment]
Here is a working example, which uses `examples/hello-world` as its base code.

```
diff --git a/examples/hello-world/hello-world.c b/examples/hello-world/hello-world.c
index e6d452d9e..f11c37ad7 100644
--- a/examples/hello-world/hello-world.c
+++ b/examples/hello-world/hello-world.c
@@ -38,15 +38,37 @@
  */
 
 #include "contiki.h"
+#include "simple-udp.h"
+#include "uiplib.h"
+
+#define UDP_PORT 10000
 
 #include <stdio.h> /* For printf() */
 /*---------------------------------------------------------------------------*/
 PROCESS(hello_world_process, "Hello world process");
 AUTOSTART_PROCESSES(&hello_world_process);
 /*---------------------------------------------------------------------------*/
+static void
+udp_rx_callback(struct simple_udp_connection *c,
+                const uip_ipaddr_t *sender_addr,
+                uint16_t sender_port,
+                const uip_ipaddr_t *receiver_addr,
+                uint16_t receiver_port,
+                const uint8_t *data,
+                uint16_t datalen)
+{
+  printf("recv a packet from ");
+  uiplib_ipaddr_print(sender_addr);
+  printf(" to ");
+  uiplib_ipaddr_print(receiver_addr);
+  printf("\n");
+}
+/*---------------------------------------------------------------------------*/
 PROCESS_THREAD(hello_world_process, ev, data)
 {
   static struct etimer timer;
+  static struct simple_udp_connection udp_conn;
+  simple_udp_register(&udp_conn, UDP_PORT, NULL, 0, udp_rx_callback);
 
   PROCESS_BEGIN();
 

```

This code gives outputs shown below, where the log level of IPv6 is set to DBG:

```
[INFO: IPv6      ] packet received from fe80::102a:b115:628f:67b5 to ff02::1
[INFO: IPv6      ] Receiving UDP packet
[DBG : IPv6      ] Upper layer checksum len: 12 from: 40
[INFO: IPv6      ] lport 10000, rport 0, addr ::
[DBG : IPv6      ] In udp_found
recv a packet from fe80::102a:b115:628f:67b5 to ff02::1
```

Enjoy hacking!

**Comment by jeandudey** [comment]
@yatch Thanks! it worked great.

**Pull request closed without merging**
