### PR TITLE
keep TSCH timesource state consistent with RPL parent state

### LINKED ISSUE #608: RPL clique reconnection problem
I'm observing an issue which prevents nodes to reconnect to the network under a particular circumstance. @manoj6932 has reported a similar issue on gitter.
Here is how I think the problem can be replicated:
 
I started from a fresh installation of Contiki-NG v 4.1 (although the problem seems happening also under the develop branch). I'm using the rpl-udp example, modified to use TSCH and Orchestra with default parameters. I'm using 3 ReMOTEs rev b. Then follow the steps:

1. start with
Node A: coordinator, visible by node B
Node B: visible by both A and C
Node C: visible by node B.

2. Network starts, nodes are transmitting and everything is cool. Coordinator shows the routes: B->A; C->B->A.

3. Move B close to C, and make sure that A does not see any other node.

4. After ~5/10 minutes, move node C where B was. This means that:
A sees C
C sees both A and B
B sees C

5. Here is the problem, now the network does not recover, meaning that neither C or B are able to establish a route to A.
Also, moving B closer to A (so that all nodes are visible to each other ~~, as it can be verified by the shell command 'ip-nbr'~~) does not solve the problem.
B and C keep printing: ```dis_input: not in an instance yet, discard```

6. Switching off either B or C, makes the other node disconnect from the network and eventually connect back to A (after a bunch of ```re-synchronizing on B``` in case B is off, printed by C)

On Cooja, same scenario, everything works fine.

It seems that B and C keep synchronizing to each other, ignoring A...

### LINKED ISSUE #890: TSCH timesource selection issues
This is relevant to the #877. Infinite loops may show up in the TSCH timesource tree. Instead of completely hijacking Adam's issue with multiple related problems, here is a new one.

First, a minor comment: the condition in the https://github.com/contiki-ng/contiki-ng/blob/develop/os/net/mac/tsch/tsch.c#L367 seems wrong? It will update the `last_eb` with the current Eb's source address if and only if there is no timesource, or the current `last_eb` address is not the same as the timesource address. As you can see, this will very soon converge to the `last_eb` address being equal to the timesource's address. I'm either misunderstanding something or guessing the if statement is meant to check the frame's source address instead of the `last_eb` address.

Fortunately, the current behavior minimizes the chance that an alternative timesource is selected and so reduces the probability the loop shows up.

Setup to replicate the timesource loop:
Network topology: 1 is the coordinator, 2 and 3 are peer nodes are in direct reachability of 1.
Routing is RPL lite, default settings (`examples/6tisch/simple-node/project-conf.h`).

With the `develop` branch:
* 0:00 - start all nodes
* around 1:00: remove root
* 1:15-1:30 - the node 2 switches to 3 as its timesource and 3 switches to 2 as its timesource
* 1:50 - RPL switches parent to NULL

With the `develop` branch, and after changing the line 367 in `tsch.c`:

    if(ts == NULL || !linkaddr_cmp(&last_eb_nbr_addr, &ts->addr)) {

to this:

    if(ts == NULL || !linkaddr_cmp((linkaddr_t *)&frame.src_addr, &ts->addr)) {

* 0:00 - start all nodes
* around 1:00: remove root
* 1:06 - the node 2 switches to 3 as its timesource and 3 switches to 2 as its timesource
* 12:04 - RPL switches parent from 1 to the peer node (2 or 3)
* 12:04-12:33 - RPL continues switching between no parent (NULL) to the peer node as a parent
* 12:33 - RPL switches parent to NULL

In both cases the TSCH timesource never becomes NULL. This will cause "islands" to form in the network and drift away from the coordinator's clock. Since they never leave TSCH network, they will never get to resync again (unless accidentally drifting back in the TSCH timing and hearing some packets).

My recommendation is to remove the alternative TSCH timesource selection, and in general keep the tsch timesources consistent with RPL parent (e.g. leave the TSCH network when RPL parent becomes NULL).

### PR DESCRIPTION
**Pull request by atiselsts**
Fixes #890 and #877

Potentially fixes #608

### CODE REVIEW

**Comment by debug-ito** [comment]
Hmm, I thought about the implication of this change, but in the end, I think it's ok.

- When a node joins a TSCH/RPL network, first it associates with the TSCH PAN (sets the time source) and then it determines the RPL preferred parent. This means there has to be a time period when the node has a TSCH time source but no RPL preferred parent. This change allows that time period, I think, because `RPL_CALLBACK_PARENT_SWITCH` is called only when `old != new`. In the joining phase, `old == new == NULL`, I think.
- What will happen after calling `tsch_queue_update_time_source(NULL)` in `RPL_CALLBACK_PARENT_SWITCH`? I think the node cannot update the `last_sync_asn` in `tsch-slot-operation.c` anymore, and call `tsch_disassociate()` eventually. We don't need to call `tsch_disassociate()` in `RPL_CALLBACK_PARENT_SWITCH` (but maybe we should??)

Well, maybe we should run some simulation experiments...

**Comment by debug-ito** [comment]
Although it's ok for me, the change in the behavior of TSCH layer is significant. Maybe we should have a way to roll it back.

For example, we can add a new configuration macro that switches between the old behavior (i.e. change time source to non-NULL RPL parent only) and the new behavior. The default behavior can be the new one, I think.

**Comment by atiselsts** [comment]
I'm against introducing any more configuration constants for features like this. In the long run, they make the OS more difficult to use and understand.
So, I'm afraid I disagree with you here.

**Comment by debug-ito** [comment]
OK. Please make sure you advertise this change in the ChangeLog of the next version.

**Pull request merged**
