### PR TITLE
ICMPv6 Destination Unreachable

### PR DESCRIPTION
**Pull request by simonduq**
This PR sends an ICMPv6 Destination Unreachable message back to the originator whenever a destination is not reachable.

### CODE REVIEW

**Comment by simonduq** [comment]
The problem is a bit tricky: the root chooses not to use the fallback interface for anything belonging to the RPL prefix, e.g. fd00::/64. But when we get a ping directly from the host computer, the source address is typically fd00::1, that is, belongs to the prefix while being behind the fallback interface.

Not sure what a clean fix would be. Suggestions?

**Comment by yatch** [comment]
I believe it is the same issue as what I had in my local project. One difference is fe80::/10 was used in my case. I have a *dirty* fix, by the way :-)

**Comment by simonduq** [comment]
What does the dirty fix do? Suggestions for a clean version of it? A full fix would probably require multiple-interface support...

**Comment by yatch** [comment]
The idea is to remember the source address of a packet from the SLIP interface so that a sending packet is going through SLIP when its destination matches the remembered source address. This matching is done before `uip_ds6_is_addr_onlink()` in `get_nexthop()`.

Having a host route entry with an outgoing interface, SLIP in this case, could be fine for this particular scenario. In any case, the target of this would be release after next.

**Comment by yatch** [comment]
@simonduq 

> The problem is a bit tricky: the root chooses not to use the fallback interface for anything belonging to the RPL prefix, e.g. fd00::/64. But when we get a ping directly from the host computer, the source address is typically fd00::1, that is, belongs to the prefix while being behind the fallback interface.
>
> Not sure what a clean fix would be. Suggestions?

`net-demux` proposed in PR #1021 could be a solution.

I have a border router running on a Linux host. The border router has IPv6 addresses shown below:

```
#0102.0304.0506.0708> ip-addr
Node IPv6 addresses:
-- fd00::302:304:506:708
-- fe80::302:304:506:708
```

From the Linux host, I can ping to both of the addresses:
```
user@6bbd0dc70152:~/contiki-ng$ ping6 -c 3 fd00::302:304:506:708
PING fd00::302:304:506:708(fd00::302:304:506:708) 56 data bytes
64 bytes from fd00::302:304:506:708: icmp_seq=1 ttl=64 time=0.229 ms
64 bytes from fd00::302:304:506:708: icmp_seq=2 ttl=64 time=0.248 ms
64 bytes from fd00::302:304:506:708: icmp_seq=3 ttl=64 time=0.207 ms

--- fd00::302:304:506:708 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2078ms
rtt min/avg/max/mdev = 0.207/0.228/0.248/0.016 ms

user@6bbd0dc70152:~/contiki-ng$ ping6 -I tun0 -c 3 fd00::302:304:506:708
PING fd00::302:304:506:708(fd00::302:304:506:708) from fd00::1 tun0: 56 data bytes
64 bytes from fd00::302:304:506:708: icmp_seq=1 ttl=64 time=0.228 ms
64 bytes from fd00::302:304:506:708: icmp_seq=2 ttl=64 time=0.211 ms
64 bytes from fd00::302:304:506:708: icmp_seq=3 ttl=64 time=0.165 ms

--- fd00::302:304:506:708 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2007ms
rtt min/avg/max/mdev = 0.165/0.201/0.228/0.029 ms
```

The default route of the border router is pointed to `tun0` of the Linux host.

```
#0102.0304.0506.0708> routes
Default route:
[INFO: IPv6 Route] Default route, IP address fd00::1
[INFO: IPv6 Route] Default route found, IP address fd00::1
-- fd00::1 (lifetime: infinite)
Routing links (5 in total):
-- fd00::302:304:506:708  (DODAG root) (lifetime: infinite)
-- fd00::201:1:1:1  to fd00::302:304:506:708 (lifetime: 960 seconds)
-- fd00::202:2:2:2  to fd00::201:1:1:1 (lifetime: 960 seconds)
-- fd00::203:3:3:3  to fd00::202:2:2:2 (lifetime: 960 seconds)
-- fd00::204:4:4:4  to fd00::203:3:3:3 (lifetime: 960 seconds)
No routing entries
```

Here are log messages of the border router when it received a ping from the Linux host having `fd00::1` on `tun0`:

```
[INFO: IPv6      ] packet received from fd00::1 to fd00::302:304:506:708
[INFO: IPv6      ] icmpv6 input length 104 type: 128
[INFO: ICMPv6    ] Received Echo Request from fd00::1 to fd00::302:304:506:708
[INFO: ICMPv6    ] Sending Echo Reply to fd00::1 from fd00::302:304:506:708
[INFO: IPv6      ] Sending packet with length 104 (64)
[INFO: RPL       ] SRH creating source routing header with destination fd00::1
[INFO: RPL       ] SRH node not found, skip SRH insertion
[DBG : RPL       ] no SRH found
[INFO: IPv6 Route] Looking up route for fd00::1
[WARN: IPv6 Route] No route found
[INFO: IPv6 Route] Default route, IP address fd00::1
[INFO: IPv6 Route] Default route found, IP address fd00::1
[DBG : 6LBR-DEMUX] Route a packet for 0200.0000.0000.0001 to the uplink
```

**Comment by joakimeriksson** [comment]
I did put a timeout on this - will anyone update this and bring it out of WIP-state?

**Comment by joakimeriksson** [comment]
Closing due to timeout.

**Pull request closed without merging**
