### PR TITLE
Contrib/simplelink base demo enhanced

### PR DESCRIPTION
**Pull request by jsolderitsch**
This request extends PR 1290.

It fixes the HDC sensor erroneous values issue.

The mpu sensor is still not enabled for Simplelink.

It also adds support for the LPSTK SensorTag based on cc1352r. Only the OPT and HDC sensors are supported; there are no BMP or TMP sensors on the new LSPTK.

base-demo.c did not enable LED display with a sensortag button push for the cc1350, so LEDS_ALL was substituted.

### CODE REVIEW

**Comment by g-oikonomou** [comment]
Changed base to branch `release-4.6`

We'll review this in detail after #1283 and #1290 as it may need a little bit more work. Thanks @jsolderitsch

**Comment by g-oikonomou** [comment]
@jsolderitsch 

Hi James. As you may have seen from notification noise, Alex and I have been going through / fixing / merging various simplelink sensor-related PRs. #1283 and #1290 are in, #1285 we are working on improving with respect to the MPU code.

Given the amount of work required to get things to work to a good standard, we have deferred the lot to the next release in spring. This gives us time to get things done properly.

There is a lot of good code here in your PR. Do you think you can do a clean code rebase in order to exclude from the history here all the commits that are already part of branch develop? Once we have a clean history, we'll give you some change requests.

@alexstanoev ping for info.

Always happy to support with git-related commands - poke us on gitter. Thanks for your time to contribute to the project!

**Comment by jsolderitsch** [comment]
I did the rebase, I think successfully, but I did not push the local rebase changes to this PR branch. How do I do that?

**Comment by g-oikonomou** [comment]
@jsolderitsch 

Hi there James. #1451 applies a fix for the TMP and HDC sensors, which I see you have also done here partially. Unfortunately merging that PR causes a conflict here again.

The LPSTK support is a significant feature addition and I would recommend keeping moving it to its own PR.

There are many `#if SENSORTAG_LPSTK`. I think we should have a think for ways to deal with the differences between boards in a better way where possible.

I see you are using `//` comments. We always use C comments `/* ... */`

Let us know how we can help, there is a lot of desirable content here.

@alexstanoev

**Comment by jsolderitsch** [comment]
> @jsolderitsch
> 
> Hi there James. #1451 applies a fix for the TMP and HDC sensors, which I see you have also done here partially. Unfortunately merging that PR causes a conflict here again.
> 
> The LPSTK support is a significant feature addition and I would recommend keeping moving it to its own PR.
> 
> There are many `#if SENSORTAG_LPSTK`. I think we should have a think for ways to deal with the differences between boards in a better way where possible.
> 
> I see you are using `//` comments. We always use C comments `/* ... */`
> 
> Let us know how we can help, there is a lot of desirable content here.
> 
> @alexstanoev

How do I learn what the conflict is?? I would be happy to work to remove the conflict if I can learn what it is!

How do I "move it to its own PR"

I will abide by whatever you choose to adopt in "deal with the differences between boards". At this point, the 1352r1 board requires such differences to be handled. You guys are the ones to chose how this is done.

I will change my comment style going forward and if I see recent comments that I made in the `//` style I will use the preferred style.

Is #1451 already merged into develop?

**Comment by g-oikonomou** [comment]
Yes #1451 is in.

> How do I "move it to its own PR"

You will need to create a new branch in your local space. In that branch, create commits that are specific to adding support for LPSTK. I see that here you have LPSTK support bundled up with other stuff, so in all likelihood you will need to re-create those commits. Then push that new branch in your origin and create a new PR entitled something like "Add support for LPSTK to the SimpleLink platform".

One possible way to approach things would be along the following lines:

```
git checkout contrib/simplelink-base-demo-enhanced
# You are now looking at all the changes here.

# Create a new branch for LPSTK
git checkout -b contrib/lpstk

# Undo all commits in that branch
git reset develo

# This will put you in a state where all the changes in this PR here are still showing as changed in your local space, but they are no longer committed.
# Apply code style changes e.g. to change the C++ comments to C comments

git add `LPSTK stuff only`
git commit -m "Add support for LPSTK"
git push origin contrib/lpstk

# At which point you can create a new PR against develop.
```

You can then switch back to this branch used for this PR here and remove all LPSTK-related changes, leaving everything else. You can always use `git reset develop` as above to undo commits and to throw away LPSTK support-related changes. Once done, if you try to rebase on top of latest develop git will complain about conflicts. It will show you exactly where the conflicts are.

**Comment by jsolderitsch** [comment]
This PR is obsolete, replaced by #1464.

**Pull request closed without merging**
