### PR TITLE
fix temperature sensor reading in nrf52dk platform, which was stuck a…

### PR DESCRIPTION
**Pull request by zhitaoh**
The blink-hello example for the nrf52dk platform display temperature samples stuck at zero:
...
temp: 0.00
temp: 0.00
temp: 0.00
...

After fixing the temperature sensor driver's value() function by adding a proper sequence of HAL statements from the NRF SDK, the blink-hello example shows correct temperature values in degree Celsius:
...
temp: 22.50
temp: 22.25
temp: 22.75
...

### CODE REVIEW

**Comment by atiselsts** [comment]
Maybe it's better to use the new `RTIMER_BUSYWAIT_UNTIL` macro (https://github.com/contiki-ng/contiki-ng/blob/develop/os/sys/rtimer.h) with a time limit instead of the unconditional `while` loop here:

    while(NRF_TEMP->EVENTS_DATARDY == 0);

**Comment by g-oikonomou** [comment]
Agree with Atis. What time durations are we looking at? If too long, best re-written as asynchronous, with events?

**Comment by zhitaoh** [comment]
Agree! I was half lazy to check the timing requirement and half curious to see if you guys would slack off with the reviewing. The datasheet says it takes typically 36 us to take a sample - I think it is short enough to just busy wait for the result. Have updated using `RTIMER_BUSYWAIT_UNTIL()` as Atis suggested.

**Comment by g-oikonomou** [comment]
@atiselsts are you happy here?

**Comment by atiselsts** [comment]
:+1:

**Pull request merged**
