### PR TITLE
Add Vagrant support

### PR DESCRIPTION
**Pull request by sieben**

### CODE REVIEW

**Comment by simonduq** [comment]
Hi. That's wonderful. Thanks. :)
Do you think you could put together a quick tutorial for the wiki? We draft wiki pages at https://github.com/contiki-ng/wiki-sandbox

**Comment by simonduq** [comment]
What would you think about also shipping `docker-ce` as well as the Contiker image, for easy local CI testing?

**Comment by sieben** [comment]
Yup that's a good idea I'm going to add it.

Le mar. 30 janv. 2018 à 20:31, Simon Duquennoy <notifications@github.com> a
écrit :

**Comment by sieben** [comment]
I have a bad news. I don't think docker support 32 bits architecture :\ 
https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-docker-ce-1
Is the 32 bits architecture really mandatory?

**Comment by simonduq** [comment]
I vote for 64-bit in Vagrant then, more future-proof. Only thing that will not work is cooja motes. But these will work through Docker anyway (as it has 32-bit libs).

**Comment by sieben** [comment]
Done.

2018-01-31 12:43 GMT+01:00 Simon Duquennoy <notifications@github.com>:

**Comment by simonduq** [comment]
OK, so, is this ready? Do you think you could draft a getting started page on the sandbox wiki?

**Comment by simonduq** [comment]
Yes, `make` under `./tests/` will run the whole test suite, but we expect it to fail anyway because of the 64-bit arch not supported by Cooja. I would instead suggest you try only the compile tests, by running `make` from `./tests/*compile*` subdirs.

Another thing that would be nice is to add the `contiker` alias to `~/.profile` as described in https://github.com/contiki-ng/contiki-ng/wiki/Docker#setup

**Comment by g-oikonomou** [comment]
This is really cool 👍 I tried to test it but can't be bothered with downloading the ubuntu image right now.

Should we also install python-magic and intelhex packages? (Used by cc2538-bsl)

**Comment by g-oikonomou** [comment]
Probably uncrustify too

**Comment by sieben** [comment]
I will add those packages to the bootstrap.sh script.

**Comment by g-oikonomou** [comment]
@sieben where are we on this one Remy? We are keen to move it forward.

**Comment by sieben** [comment]
I've added the packages you asked for. I've you run bootstrap.sh just after
the vagrant up? vagrant up can hang for very long commands, that's why I
prefer to use a bootstrap.sh scripts next to it.

**Comment by simonduq** [comment]
@sieben well cann't run the `.sh` as I don't even have `contiki-ng` in my homedir it seems :p

**Comment by sieben** [comment]
That's strange, the contiki-ng that contains the Vagrantfile is supposed to
be sync with the one inside the VM. Is there other file inside your $HOME
when you are in the vagrant box?

Le mer. 28 févr. 2018 à 15:23, Simon Duquennoy <notifications@github.com> a
écrit :

**Comment by simonduq** [comment]
This is what I get:
```
C:\Users\simon\work\dev\contiki-ng\tools\vagrant>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/xenial64' is up to date...
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

C:\Users\simon\work\dev\contiki-ng\tools\vagrant>vagrant ssh
Welcome to Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-116-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.


Last login: Mon Feb 26 09:20:17 2018 from 10.0.2.2
vagrant@ubuntu-xenial:~$ pwd
/home/vagrant
vagrant@ubuntu-xenial:~$ ls
vagrant@ubuntu-xenial:~$
```

**Comment by simonduq** [comment]
Yeah now with offline support from @sieben it seems to work :) Basically did `vagrant destroy` and `vagrant up` again.

**Comment by sieben** [comment]
It could be a glitch. vagrant destroy and vagrant up should fix this.

Le mer. 28 févr. 2018 à 16:14, Simon Duquennoy <notifications@github.com> a
écrit :

**Comment by sieben** [comment]
dos2unix ./contiki-ng/tools/vagrant/bootstrap.sh could be useful in case
you are in windows

Le mer. 28 févr. 2018 à 16:51, Simon Duquennoy <notifications@github.com> a
écrit :

**Comment by simonduq** [comment]
Trying this again and for some reason every single step seems to fail so far :p
For instance, after downloading / unpacking / copying the ARM compiler, I get:
```bash
vagrant@ubuntu-xenial:~/contiki-ng$ whoami
vagrant
vagrant@ubuntu-xenial:~/contiki-ng$ whereis arm-none-eabi-gcc
arm-none-eabi-gcc: /usr/local/bin/arm-none-eabi-gcc
vagrant@ubuntu-xenial:~/contiki-ng$ ll /usr/local/bin/arm-none-eabi-gcc
-rwxr-xr-x 1 root root 776368 Mar  2 12:22 /usr/local/bin/arm-none-eabi-gcc*
vagrant@ubuntu-xenial:~/contiki-ng$ /usr/local/bin/arm-none-eabi-gcc
-bash: /usr/local/bin/arm-none-eabi-gcc: No such file or directory
```

**Comment by sieben** [comment]
Maybe this is a bash problem. What happens when you use a different
shell? Dash/Zsh do you get similar results?

Le ven. 2 mars 2018 à 13:29, Simon Duquennoy <notifications@github.com> a
écrit :

**Comment by simonduq** [comment]
The problem was lack of support for 32-bit binaries. I added a number of fixes as https://github.com/sieben/contiki-ng/pulls

Now thinks still don't work smoothly, e.g., compilation for a number of platforms such a sky, as well as Docker. Happy to get this merged as soon as the full test suite passes.

**Pull request merged**
