### PR TITLE
Initial nrf52840 port

### PR DESCRIPTION
**Pull request by warner83**
This is an initial port for the nrf52840-dk board. The PR is a joint work with Zhitao He @zhitaoh 

The port is based on the existing nrf52dk code, modified to adopt the nRFSDK v15.2 (nRF5SDK15209412b96). 

Initial support for radio is obtained by integrating the Nordic Semiconductor 802.15.4 driver (https://github.com/NordicSemiconductor/nRF-IEEE-802.15.4-radio-driver/). 
TSCH support partial (still having timing issues).

### CODE REVIEW

**Comment by g-oikonomou** [comment]
Thanks for this!

Clearly quite a bit of work to be done in terms of documentation, code style etc.

Some things I can immediately think:
* Are you planning to retain BLE support and soft device?
* We have many cortex-related facilities under `arch/cpu/arm/`, please try to re-use as much of that as possible. I think you may be able to remove some duplication at least from a build system perspective.
* I see that you are introducing a new platform dir, but there also seem to be changes under the current ` arch/platform/nrf52dk/`. Can you explain the motivation please?
* It would be really really cool to see support for the GPIO HAL and remove the legacy `button-sensor` and `leds-arch`.

**Comment by warner83** [comment]
> Thanks for this!

Thank you for the initial feedback!

> 
> Clearly quite a bit of work to be done in terms of documentation, code style etc.

I know, this is still WIP, I'll improve them in the next iterations.

> 
> Some things I can immediately think:
> 
>     * Are you planning to retain BLE support and soft device?

Yes definitely, I'll work on them as soon as I've complete 15.4 support. 

> 
>     * We have many cortex-related facilities under `arch/cpu/arm/`, please try to re-use as much of that as possible. I think you may be able to remove some duplication at least from a build system perspective.

Ok, sure, I'll take a look!

> 
>     * I see that you are introducing a new platform dir, but there also seem to be changes under the current ` arch/platform/nrf52dk/`. Can you explain the motivation please?

My bad! The changes under the ` arch/platform/nrf52dk/` dir are from a set of commits I reverted before the PR. I missed a couple. I'll clean them up. 
The idea was to create a new platform for a smooth transition, since the nrf52840 requires an updated version of the nrfSDK. In the long term, all the nrf52 boards could be supported by a single platform dir (?).

> 
>     * It would be really really cool to see support for the GPIO HAL and remove the legacy `button-sensor` and `leds-arch`.

Yes, I agree. I'll add in the TODO list.

**Comment by g-oikonomou** [comment]
> In the long term, all the nrf52 boards could be supported by a single platform dir (?).

That would be very desirable, yes

**Comment by pgrzesik** [comment]
Hello, is there any progress on support for nrf52840?

**Comment by warner83** [comment]
Hi, unfortunately, I had no spare time in the last months to finalize it. 
All functions are there except for TSCH support.
We need only some final testing and cleaning.
I'll try to wrap up in the next months. 
@zhitaoh any luck on your side?

**Comment by zhitaoh** [comment]
Hi! Thanks for asking and putting pressure! I am on the same page as Carlo, pledging some of my spare time in near future, but not yet in action at this moment. I have on my TODO list debugging the TSCH implementation. I have a quite reliable HW set-up here that can log radio on/off and TX/RX states of up-to-four nRF52840DK's simultaneously, to a time resolution of 0.1 us. I have also found a trick to log the chip's internal channel hopping events in real time. So I just need a bit of spare time, to help resolving some delicate TSCH timing issues.

**Comment by warner83** [comment]
Wonderful!
I'll try to find some spare time in the following weeks to resolve the conflicts and clean up.

**Comment by g-oikonomou** [comment]
#1310 added support for the nRF52840, for .15.4 mode only and without using the soft device. This pull here does use the soft device so perhaps value in revisiting in the future depending on what we decide to do with BLE in the long term.

For now, I'm closing this

**Pull request closed without merging**
