### PR TITLE
Tidy-up the examples directory

### PR DESCRIPTION
**Pull request by g-oikonomou**
This pull starts a tidy-up of the examples directory.

* Some obsolete examples and associated tests have been removed
  * rpl-simple: As discussed the other day, no longer serves a purpose
  * json-ws: Was not building for any of the platforms I tried
  * extended-rf-api: No longer serves a purpose
* All examples under ipv6/ have been moved to the top-level `examples/` dir. Associated tests and simulations updated.
* New platform-independent example: UDP echo server (was under cc2538dk with no good reason)
* The mess of a webserver config for native-border-router and rpl-border-router has been improved.

Sits on top of #121

This is still WiP, but I thought I'd open to discussion. Still to come:
* [ ] Cross-platform MQTT client example (will need #122)
* [x] Fixes for better cross-platform support in slip-radio (done in #131 and #133) and rpl-border-router (done in #132) (will need #122). 
* [x] Finalise to rpl-udp and udp-ipv6
* [ ] rpl-tsch-sixtop: Change .csc to use Cooja motes instead of Z1s. Could someone help @nfi @joakimeriksson @simonduq?

### CODE REVIEW

**Comment by simonduq** [comment]
@yatch comments on the sixtop csc file?

**Comment by yatch** [comment]
@simonduq @g-oikonomou I'll work on `rpl-tsch-sixtop`.

**Comment by simonduq** [comment]
@yatch note that we in a bit of a hurry here, we will announce the release this week. Shout if you have no time to address this in the next days

**Comment by g-oikonomou** [comment]
If that's the case we can simply delete the Z1 version and then add something later on.

**Comment by simonduq** [comment]
I feel we could improve clarity further:
* mandate a readme for each example?
* proposal: add some structure, e.g. "networking", "storage", "libs"

There are some examples for which I have no clue what they do, I suggest to either add readme or remove:
* eeprom-test: no clue what this is
* http-socket vs websocket: what is the difference, do we need both?
* udp-echo-server: would remove, so we focus on simple-udp, unless we see a valid reason to still support/document the other API?
* packet-processing: unclear name and no readme
* minor: move antelope/shell to antelope?

(happy to take care of doing this, only want to check here what people think first)

**Comment by g-oikonomou** [comment]
As long as we don't end up with 90% of the examples under networking/.

eeprom-test seems to be getting used by platform native. Perhaps we should move to platform-specific. I'll have another look at the UDP stuff. I do want to finish the work on slip-radio and border-router first.

**Comment by simonduq** [comment]
Let me look into this, so you keep your focus on slip-radio and BR. Will get back with a comment or PR on your branch later today!

**Comment by nvt** [comment]
antelope/shell can indeed be moved up to antelope. There is only one Antelope example now since the Rime-based remote DB example was removed, and there probably won't be more examples added in the nearest future.

**Comment by yatch** [comment]
`rpl-tsch-sixtop-cooja.csc` and related files are ready by https://github.com/yatch/contiki-ng/commit/ec6d49b128b9e1dcb6a543aa1ddee3bda4d1bf32

**Comment by simonduq** [comment]
@g-oikonomou let me cherry-pick this and have it in my PR to your branch (because I'm moving these files around)

**Comment by simonduq** [comment]
Opened a PR https://github.com/g-oikonomou/contiki-ng/pull/1

The border router / slip-radio examples could also be reorganized a bit, but I didn't touch as I know you're working on it and not sure what you have in mind. Ideas:
* move slip-radio inside native-border-router, as these two really are inter-dependent
* more consistent naming between rpl-border-router and native-border-router. The latter maybe becomes rpl-border-router-native? or moves inside rpl-border-router?

**Comment by simonduq** [comment]
I've worked more on https://github.com/g-oikonomou/contiki-ng/pull/1 , with a complete rework of example `rpl-udp`. It is ready (assuming Travis green  -- not sure why testing takes time right now)

**Comment by g-oikonomou** [comment]
Thanks @yatch @simonduq all pulled in and pushed here, nicely rebased on top of previous merged stuff.

Not hugely keen on moving slip-radio inside the native-border-router dir, since people do tend to use it a lot with 6lbr (which btw is something we should aim to support strongly but without reinventing it)

**Comment by g-oikonomou** [comment]
All done with slip-radio and border-router for now.

Perhaps something like:
```
border-router/
  native/
  embedded/
```
?

Should be very straightforward git-moving and changing csc files and travis tests.

**Comment by simonduq** [comment]
Great. I would propose to also move `slip-radio` closer to the native br. Maybe just add to the `border-router` directory you're proposing?

**Comment by simonduq** [comment]
Build is stuck because trying to build `udp-echo-server`, which was removed (see `/tests/02-compile-arm-ports/Makefile `)

**Comment by simonduq** [comment]
This is ready for merging IMO once travis is happy again!

**Comment by simonduq** [comment]
@g-oikonomou I agree regarding 6lbr as well. Regarding BR sub-directories, I vote for your proposal above.

**Comment by joakimeriksson** [comment]
Regarding 6lbr - we need to figure out what we want - we have a significantly updated native-border-router and serial-radio in sparrow also. Let's take that discussion up to the roadmap next release. We need to have a easy way to connect things to the Internet - preferably in the repo.

**Comment by g-oikonomou** [comment]
On 6lbr, I think we should probably come up with a nice 6lbr-friendly SLIP radio that supports more commands etc and one that the 6lbr people don't have to mantain. Perhaps we should put something in the roadmap and talk to Laurent in due  course.

I've fixed the travis error and re-pushed all branches. Let's get this one in when we can.

**Comment by simonduq** [comment]
sixtop example broke, this should fix it https://github.com/simonduq/contiki-ng/commit/74abec8c790b5290664eff313548bb90f1643520

**Pull request merged**
