### PR TITLE
CC13xx radio fixes

### PR DESCRIPTION
**Pull request by atiselsts**
This adds a number of commits that should improve the reliability of CC13xx radios.

Related to #1432 and #1401.

Pinging @lili1218 @alexrayne @rajeev1986

### CODE REVIEW

**Comment by atiselsts** [comment]
Also fixes #1504

**Comment by alexrayne** [comment]
Hallow @atiselsts !
about your 3rd and 4th changes - i guess, your patches looks more cleaner with [somewhat like this ](https://github.com/alexrayne/contiki-ng/commit/083d19b3b4177477ff6ff20a313ebbf9ac3a5130) change. 
If you claims, i can provide PR with it.

**Comment by atiselsts** [comment]
Thanks for the feedback Alex. I'll see how to improve the code using this idea.

**Comment by atiselsts** [comment]
@alexrayne I think it makes sense to develop this simplification idea and just get rid of the second argument of rf_core_send_cmd() function. It is often not used, or only used when PRINTF are enabled.

This could be part of a new PR. Here is a branch that implements this: https://github.com/atiselsts/contiki-ng/commit/669694984db0283bd3ebf04579d425644def89d9

**Comment by atiselsts** [comment]
Tested again with CSMA - seems working fine as long as security is not enabled. The CSMA timing issue when security is enabled remains - I'm currently investigating it, it needs a separate fix.

**Review by g-oikonomou — APPROVED** [review]

**Pull request merged**
