### PR TITLE
Add libraries and example for common data structures

### LINKED ISSUE #208: Libraries for common data structures
It would be nice to provide libraries with implementations of common data structures. In the first instance, I am thinking doubly linked lists, circular lists, queues, stacks. Naturally, there is nothing preventing us from providing libraries for more advanced data structures.

### PR DESCRIPTION
**Pull request by g-oikonomou**
This pull adds libraries for:

* Stacks
* Queues
* Circular, singly-linked lists
* Doubly-linked lists
* Circular, doubly-linked lists

The libraries for stacks and queues are merely wrappers around our existing list library, since it already provides all necessary functions.

The remaining ones are implemented from scratch and have no such dependency.

This pull also adds an example demonstrating / testing the above.

Closes #208

### CODE REVIEW

**Comment by g-oikonomou** [comment]
I've added doubly-linked lists. This is ready from my PoV

**Comment by simonduq** [comment]
What would you think about adding a test, e.g. by declining the example with the `unit-test` module, e.g as @yatch did in: https://github.com/contiki-ng/contiki-ng/blob/develop/tests/13-ieee802154/code-6tisch/test-sixp.c

**Comment by g-oikonomou** [comment]
I had not noticed those. Are they relying on platform cooja or can they also be sky simulations? Can they be executed on native?

**Comment by simonduq** [comment]
The 6top tests are on platform Cooja but for sure Sky would work just as well (albeit slower). This is the .js that checks the output:
https://github.com/contiki-ng/contiki-ng/blob/develop/tests/13-ieee802154/js/sixtop-test.js

Native also sounds like a great option, you could simply use `Makefile.script-test`, compile the example, run it and grep for failure :)

**Comment by g-oikonomou** [comment]
I've added unit tests (sky sims) for everything except circular, doubly-linked lists. Have a look if you want. I'll probably add native tests too.

@yatch I am absolutely in love with this unit test lib 😍

**Comment by g-oikonomou** [comment]
Now testing all libraries in cooja/sky + in platform native. AFAIK this is ready for review.

As a side-effect, I've added a new travis job (`08-native-runs`), where we can chuck other tests using platform native in the future.

**Comment by yatch** [comment]
@g-oikonomou I love `unit-test`, too. Thank you, @nvt, for this cool stuff :wink:

**Comment by g-oikonomou** [comment]
Now requires #246

**Comment by nvt** [comment]
It's nice to extend the library with some fundamental data structures, and I'm glad that to see that the unit test module is being used more. 👍

**Comment by simonduq** [comment]
Ah sorry for missing that earlier, but one last thing would be to add the new example as compile test: I believe we have all examples covered by tests on at least one platform, would be a pity to break this rule!

Other than that this looks ready to me, documented and tested :)

**Comment by g-oikonomou** [comment]
Added for native, sky, zoul, nrf52dk

**Pull request merged**
