### PR TITLE
Border router and native network interface CI test

### PR DESCRIPTION
**Pull request by simonduq**
Addresses https://github.com/contiki-ng/contiki-ng/issues/88

Adds the ability to run script tests, i.e., a series of `.sh` files.
The first example is a RPL BR test. Runs a simulation with BR and a couple nodes, and pings a node.
The plan is next to add NBR tests, BR tests with both MSPSim and Cooja motes and CSMA and TSCH.

This works locally on my Linux but not yet in Travis. The logs suggest that Cooja fails to open a server TCP socket on port 60001. Locally, `netstat -a` includes:
```
tcp6       0      0 [::]:60001              [::]:*                  LISTEN 
```

But it's not there in Travis:
https://travis-ci.org/simonduq/contiki-ng/builds/300247894

Not sure how to take it from here, ideas very welcome!

### CODE REVIEW

**Comment by joakimeriksson** [comment]
What about trying to get Cooja to signal when it is done opening the port? It might take different time for Cooja locally vs in Travis for booting up and opening the socket / port.

**Comment by simonduq** [comment]
I doubt it is a timing issue, there is *plenty* of slack time already. Locally, all is set after the first `sleep 5`. Here, we have another `sleep 5`, followed by a failed ping, and only then we call `netstat` and see the socket is not there.

**Comment by joakimeriksson** [comment]
Try to do 1 minute wait and see if that is better. Anything with a fixed sleep is sensitive.

**Comment by simonduq** [comment]
Well sure I'll try that

**Comment by simonduq** [comment]
any way to collect errors from the serialsocket plugin? didn't seem to be anything in the COOJA.log

**Comment by joakimeriksson** [comment]
But it seems to print success at least...  INFO [AWT-EventQueue-0] (SerialSocketServer.java:389) - Listening on port: 60001 onServerStarted.

**Comment by simonduq** [comment]
OK, did not see that. Where was this?

**Comment by joakimeriksson** [comment]
When I run Cooja locally on my OS-X with the serial socket-server is enabled on a node - it prints this on the shell (which should end up in the log then).

**Comment by simonduq** [comment]
OK, interesting. So it works locally both linux and OSX but not in Travis

**Comment by simonduq** [comment]
Oh right as pointed out by @joakimeriksson offline Travis has to build Cooja whereas on our system it's already build. This adds a lot of delay. Might basically explain it. Will try soon adding more delay!

**Comment by simonduq** [comment]
Removed the long stream of comments. Problem now solved. Summarized below:
* timing issue: there was not enough time for Cooja to start
* IPv6 disabled by default in Travis. Now enabled at init

Will add more tests now!

**Comment by joakimeriksson** [comment]
Great!!!

**Comment by simonduq** [comment]
This PR is now ready. Tests the BR on Cooja, Cooja+TSCH, and Sky. Also adds a test of the native platform network interface.

I tried native-border-router but could net get it to run reliably with Cooja. Will need more investigation. Also wanted to add a CoAP test using the native platform, with the node running a server and `coap-cli` as a client. Somehow both can talk but the server always returns `4.04`. Enabling debug in CoAP result in compilation error... perhaps things will be a lot better after https://github.com/contiki-ng/contiki-ng/pull/167 is merged!

**Comment by g-oikonomou** [comment]
Very desirable feature.

**Pull request merged**
