### PR TITLE
CI: use x64 macOS runner

### PR DESCRIPTION
**Pull request by nfi**

### CODE REVIEW

**Comment by pjonsson** [comment]
This seems to make the required jobs not match again. Is it time to bring in #2737 as well now since things have to be changed anyway?

**Review by arurke — APPROVED** [review]

**Comment by arurke** [comment]
I am not familiar with github actions - anything I can/should do here to get this moving?

**Comment by nfi** [comment]
I have updated the names for required jobs.

**Comment by arurke** [comment]
> I have updated the names for required jobs.

This is a repository setting?

**Comment by nfi** [comment]
Yes, it is configured in `Settings` -> `Branches` - > `Branch Protection Rules`.

**Pull request merged**
