### PR TITLE
Platform native: Avoid trying to use the tun when the tun is not available.

### PR DESCRIPTION
**Pull request by nfi**
This allows a native platform application to run without network.

### CODE REVIEW

**Comment by g-oikonomou** [comment]
> This PR should solve this issue.

"Should"? :D

**Comment by nfi** [comment]
>> This PR should solve this issue.
>
> "Should"? :D

"will" ;-)

**Comment by simonduq** [comment]
good catch!

**Comment by simonduq** [comment]
also tried on my linux, both with and without networking

**Pull request merged**
