### PR TITLE
Update rpl-udp example README.md

### PR DESCRIPTION
**Pull request by simonduq**

### CODE REVIEW

**Comment by simonduq** [comment]
so I'm just thinking, as per Gitflow, this minor pre-release polishing should actually go the release branch, and will be merged back to `develop` at release time. Just changed the target branch of this PR, let me know if that feels right

**Comment by simonduq** [comment]
Oops but then it includes the new renode example as well which should probably still be `develop`. Let me fix this PR

**Comment by simonduq** [comment]
This is now ready

**Comment by g-oikonomou** [comment]
Yes, this can go to the release branch

**Pull request merged**
