### PR TITLE
cooja: use linker for section info

### PR DESCRIPTION
**Pull request by pjonsson**
Define helper symbols to inform Cooja about
start addresses and sizes of segments.

### CODE REVIEW

**Comment by pjonsson** [comment]
This requires the linked Cooja PR to be merged at the same time.

**Comment by alexrayne** [comment]
what problem with adress and sizes? generated .map (and ns too) provide
this ino in  listing.


вс, 16 окт. 2022 г., 12:41 Peter A. Jonsson ***@***.***>:

**Comment by pjonsson** [comment]
Beyond the difficulty to parse the map file, the map file does not contain size information about all symbols (even when built with `-fcommon`). This patch removes the need to parse the map file.

**Comment by alexrayne** [comment]
map ddfinitely have info about all sections - org and sizes. as for symbols
- there is problem, that nm can solve, and it looks used on old cooja.
that luck of symbol info can be filled by building with --fdata-section.
That solution used in old cooja too.
i have work version of map-parser in cooja that well loads -map files,
buildt with --fdata-section.


вс, 16 окт. 2022 г., 16:37 Peter A. Jonsson ***@***.***>:

**Review by nvt — APPROVED** [review]

**Review by nfi — APPROVED** [review]

**Pull request merged**
