### PR TITLE
Fix TSCH on cc2528dk and openmote-cc2538

### LINKED ISSUE #704: It is not possible to compile the TSCH_MAC for Openmote-cc2538
I can't compile the example using TSCH for MAC layer.
- Target platform: openmote-cc2538
- Assuming a complete and functional toolchain running on Linux (Ubuntu 16.04)
- Assuming that you are at the contiki-ng root directory
- Code version: 
```
git show
commit b4a23467fadadcb613bf2dcea790f3939fddc2ff
Merge: c6b795d d85cece
```

1. Navigate to `/examples/hello-world`
2. Include the code `MAKE_MAC = MAKE_MAC_TSCH` to the Project Makefile
3. Run the `make` command: `make TARGET=openmote-cc2538 hello-world`

Expected result: successful compilation

Current result: recipe for target 'obj_openmote-cc2538/tsch-slot-operation.o' failed 

Error log: [contiki-bg-tsch-openmote-cc2538-errorlog.txt](https://github.com/contiki-ng/contiki-ng/files/2480414/contiki-bg-tsch-openmote-cc2538-errorlog.txt)

### PR DESCRIPTION
**Pull request by simonduq**
Fixes #704

### CODE REVIEW

**Comment by simonduq** [comment]
Does simplelink also support TSCH? (in which case we also want a compile test for it)

**Comment by g-oikonomou** [comment]
What I am seeing is #705

**Comment by simonduq** [comment]
But is the simplelink port supposed to support TSCH at all?

**Comment by g-oikonomou** [comment]
I haven't the slightest of clues :) Perhaps one of our users can report back since we can now build it.

**Pull request merged**
