### PR TITLE
Update 6top Protocol (6P) to draft-10

### LINKED ISSUE #178: Support draft-ietf-6tisch-6top-protocol-09
While Contiki-NG supports 6top protocol (6P), the supported draft version is [draft-07](https://tools.ietf.org/html/draft-ietf-6tisch-6top-protocol-07), which has been updated by new drafts. The latest 6P draft is [draft-09](https://tools.ietf.org/html/draft-ietf-6tisch-6top-protocol-09); need to update Contiki-NG's 6P code with it.

### PR DESCRIPTION
**Pull request by yatch**
# Summary
This PR update the 6top Protocol (6P) implementation to the latest draft, [draft-ietf-6tisch-6top-protocol-10](https://tools.ietf.org/html/draft-ietf-6tisch-6top-protocol-10).

# Impacts on Scheduling Function Implementations
## GEN field is gone
Scheduling Functions (SFs) don't need to care about the generation counter any more.

Since [draft-ietf-6tisch-6top-protocol-08](https://tools.ietf.org/html/draft-ietf-6tisch-6top-protocol-08), 6P Message hasn't had the GEN field. Scheduling inconsistency is taken care of using SeqNum. `sixp_nbr_get_gen()` and `sixp_nbr_advance_gen()` are removed by this PR.

`sixp_nbr_get_gen()` and `sixp_nbr_advance_gen()` calls in your SF code should be removed as well, otherwise you'll get compilation errors.

## SIGNAL command is available
If your SF needs to exchange something wit peers, SIGNAL command can be used for such a purpose. Both of the SIGNAL request and response have Paylaod field, in which SF-dependent information is stored. `sixp_pkt_set_payload()` and `sixp_pkt_get_payload()` are provided to manipulate the field value.

Please refer to [draft-ietf-6tisch-6top-protocol-10](https://tools.ietf.org/html/draft-ietf-6tisch-6top-protocol-10#section-3.3.7) for further information.

## Renaming Return Codes
The macros for 6P Return Codes are renamed in order to get aligned with the draft's [definitions](https://tools.ietf.org/html/draft-ietf-6tisch-6top-protocol-10#section-6.2.4).

# Miscellaneous Updates
* `examples/6tisch/6tp-packet/project-conf.h`:
  * enable debug logging for `6top`
  * bugfix in selecting TSCH coordinator
* fix typos in error messages

# Note
Fixes #178

### CODE REVIEW

**Comment by g-oikonomou** [comment]
Only had a brief look, but this looks cool! 👍

**Comment by simonduq** [comment]
Looks great. Did you have a chance to try it against OpenWSN?

**Comment by yatch** [comment]
@simonduq Unfortunately, no.

**Comment by yatch** [comment]
Needs wiki update https://github.com/contiki-ng/contiki-ng/wiki/Documentation:-6TiSCH-6top-sub-layer

**Comment by simonduq** [comment]
Let us know when you're confident enough this PR can be merged.

>

**Comment by g-oikonomou** [comment]
@yatch What's the state of this? Are we ready to pull this in?

**Comment by yatch** [comment]
I've rebased the branch and Travis should gets green. Although it's not tested with physical devices, it's ready to be merged. The example of `example/6tisch/sixtop` works without any issue. 6P packets are dissected by (the bleeding-edge) Wireshark correctly.

**Comment by simonduq** [comment]
Sounds good

**Pull request merged**
