### PR TITLE
Cleanup TSCH .h files

### PR DESCRIPTION
**Pull request by simonduq**
This re-arranges TSCH .h files to make it easier to find constants, types, and defines. This is done following the same structure as RPL Lite. Naming of many macros is also simplified as a result.

Most constants, configs and types are now moved to `tsch-const.h`, `tsch-conf.h` and `tsch-types.h`. This was not done for TSCH modules that are really standalone, such as `tsch-security`, `tsch-asn` or `tsch-log`.

An obvious next step will be to add Doxygen. Added to the roadmap: #377

### CODE REVIEW

**Comment by atiselsts** [comment]
I'm afraid that this doesn't make me too excited, seeing that TSCH users will have to change their `project-conf.h` files everywhere once again. Thought that migrating my applications from Contiki to Contiki-NG was already hard enough ;)

**Comment by simonduq** [comment]
What about just doing the re-arrangement to `tsch-conf`, `tsch-const` and `tsch-types` but preserving constant names for backwards compatibility?

**Comment by atiselsts** [comment]
Personally I have no problems with the rearrangements and like the new `tsch-types.h` file.

**Comment by simonduq** [comment]
OK will remove the name changes then. Thanks for the feedback :)

**Comment by simonduq** [comment]
Done

**Pull request merged**
