### PR TITLE
Initial support for board OpenMote-B

### PR DESCRIPTION
**Pull request by wallb**
Renamed platform ‘openmote-cc2538’ to ‘openmote’ to support multiple boards.
Added openmote-b as board under platform 'openmote' with configuration changes for openmote-b inspired by izacarias/contiki-ng fork.

### CODE REVIEW

**Comment by g-oikonomou** [comment]
Thanks for this, I've started reviewing. So far so good!

**Comment by wallb** [comment]
I have updated the doxygen structure, as suggested.

**Comment by wallb** [comment]
Just noticed the failing doxygen test. Will investigate.

**Comment by g-oikonomou** [comment]
#1084 

Let me have a look at the pull. We had a discussion the other day and considering including it in the release.

**Comment by g-oikonomou** [comment]
OK I jumped the gun, but the fix is a very simple one:

```
$ git diff
diff --git a/arch/platform/openmote/openmote-b/board.h b/arch/platform/openmote/openmote-b/board.h
index e2ba6a118..b37030a3f 100644
--- a/arch/platform/openmote/openmote-b/board.h
+++ b/arch/platform/openmote/openmote-b/board.h
@@ -216,5 +216,6 @@
 #endif /* BOARD_H_ */
 /*---------------------------------------------------------------------------*/
 /**
+ * @}
  * @}
  */
diff --git a/arch/platform/openmote/openmote-cc2538/board.h b/arch/platform/openmote/openmote-cc2538/board.h
index 8092c97de..be27088ef 100644
--- a/arch/platform/openmote/openmote-cc2538/board.h
+++ b/arch/platform/openmote/openmote-cc2538/board.h
@@ -213,5 +213,6 @@
 #endif /* BOARD_H_ */
 /*---------------------------------------------------------------------------*/
 /**
+ * @}
  * @}
  */
```

Other than that looks good 👍

**Comment by wallb** [comment]
@g-oikonomou Thanks for looking into the issue.

**Pull request merged**
