### PR TITLE
propose printf  featured with dump uip/linkaddr (like linux printk)

### PR DESCRIPTION
**Pull request by alexrayne**
this patch motivated by LOG_xxxADDR disaster in contiki code. linux core for same reason provides printk - featured for internal structures dump. with same maner here provided printing:

    -  linkaddr* -  with %pL
    -  uip_addrt*  - with %pI

* for sample, rpl-icmp6.c updated for new styled printf. just for look and feel. (in my compilaton for cc1350, size of this object for LOG_INFO verbode reduces by 300bytes)

* to avoid getting full uip stack into strformat code, there was deployed uip adress structures to standalone header `uipaddr.h` . this change not mandatory and can be droped. imho, even not affects anything.

* changes for cooja make based on #PR1211, since it is work for me, but original make i can`t debug.

* provided configuration of printf capabilities via macro PRINTF_CONF_HAVE_DOUBLE/LONGLONG/NETADDR

* fix/improve %.Ns - use precision N for string len evaluation limit. This can give tolerance vs string args, that have no \0 string ends.

* not introduced another `printfk` but override existing `printf` since this routine is huge, and not want have both versions in resulting binary. 

* to override `printf` without override system puts/char macro MAKE_WITH_LIB_DBG_IO  provided - it choose wich output printf use: dbg_xxx or system putchar

### CODE REVIEW

**Comment by alexrayne** [comment]
last changes fixes z1 platform builds, and expected to work everywhere, but lack - need inspect zoul and sky platforms now.

**Comment by alexrayne** [comment]
last 2 changes provides:
- configuration of printf capabilities via macro PRINTF_CONF_HAVE_DOUBLE/LONGLONG/NETADDR
- fix/improve %.Ns - use precision N for string len evaluation limit. This can give tolerance vs string args, that have no \0 string ends.

**Comment by alexrayne** [comment]
debuged with cooja tests, and facepalming bugs fixed, that crushes stack on numbers printing

**Comment by simonduq** [comment]
Hi!

This was my mistake, very sorry about it, re-opening this PR now.

What happened is the following: I was switching the base branch for this repository https://github.com/wittra/contiki-ng from develop to wittra. But accidentally, I made the change on the wrong repo (this repo) and instead of switching the base branch I renamed it. And somehow github deleted develop and closed all PRs...

Many apologies for this mishap 🙏; I haven't contributed in a while.. but now at least everybody got some notification from me :p

**Comment by arurke** [comment]
The benefits of this PR, the simplified logging and especially the code savings mentioned is really interesting. I would love to help move this forward. @alexrayne Is this PR ready for review? Are there commits that are not relevant and can be separated into another PR? Would you mind rebasing on the develop branch since we have a lot of Makefile changes lately?

Reading a bit on printk I see indeed that [Linux have this functionality](https://www.kernel.org/doc/html/latest/core-api/printk-formats.html#ipv4-ipv6-addresses-generic-with-port-flowinfo-scope), which is promising. I have no experience with this part of the code - shameless ping to @pjonsson , I see you have some commits here and some focus on code-size lately - would you be willing to have a look if this PR has merit?

**Comment by alexrayne** [comment]
Hallow @aruke ! i works with this code since year ago. For that version it was ok. 

From that time there was critical changes conflicts with this PR: 

Cooja had some wraps on printf, that forces cooja code use `os/lib/dbg-io/snprintf.c` for printf - and guaranty that cooga simulation prints same as embedded target code.

But a few month ago somebody has need printing floats in cooja simulation log. And, instead of provide float printing in contiki library `os/lib/dbg-io/snprintf.c`, they are drop using contiki printer, and use native libc printf. 

Only way alive this PR - somehow revets back that change. If you can promote this  - it would great for me (i have to use my local version of code now, and merges with develop branch).

I can rebase and some cleanup this code on devel branch for you, but you have to polishing it for main repo PR byself (guess my code never acepts for some reason). So, if made new PR into your repo, do you interest it?

**Pull request closed without merging**
