### PR TITLE
oppila platform

### PR DESCRIPTION
**Pull request by Oppila-Microsystems**
oppila platform comprises the powerful CC2538 with 32-bit ARM Cortex-M3 (32MHz, 32KB RAM and 512KB flash) System on Chip (SoC), USB 2.0 and a built-in 2.4 GHz compatible with the IEEE 802.15.4 standard.

OMote is a lightweight and powerful IOT development board, with 3 on board sensors like LDR, BMP180 and Accelerometer. The omote is an ultra-low power hardware platform for real time IOT applications. The micro-USB is used for both powering the device over USB (5VDC),and programming/debugging using the BSL. Bootloader should be unlocked by manually pressing the BSL button and reset button. board can be flashed using following command

make TARGET=oppila oppila-demo.upload

The orouter is a routing device that forwards data packets between networks.It is capable of IPV4/IPV6 routing device.The device integrates the ENC28J60
ethernet module, supporting up to 30VDC.The micro-USB is used for both powering the device over USB (5VDC),and programming/debugging.Bootloader should be unlocked by manually pressing the BSL button and reset button. board can be flashed using following command

make TARGET=oppila BOARD=orouter oppila-demo.upload

### CODE REVIEW

**Comment by g-oikonomou** [comment]
In response to your queries on gitter: The conflicting file has been changed by a couple of pull requests for example #1286 and #1343 since the point in time when you created your branch. You will need to rebase your PR branch on top of the current version of branch develop locally and resolve the conflict manually. Once you have finished that, force push your branch and this will make the error go away.

I also see in your PR that you are adding many new tests. Of those, we only need the following three:

```
platform-specific/oppila/orouter/client/oppila:BOARD=orouter \
platform-specific/oppila/orouter/ip64-router/oppila:BOARD=orouter \
platform-specific/oppila/oppila \
```

You don't need to add tests to the out-of-tree build.

If you are going to rebase the PR to fix this error, I strongly suggest cleaning up your history. Commit messages are not in a good shape at the moment.

This is a good example of what a good platform-adding PR could look like: contiki-ng/contiki-ng#1310

Is this a commercially-available product? If the PR gets merged, will you be looking after the port in the longer term?

We will also need a wiki documentation page, but this can wait till the PR is in a good shape.

Thanks!

**Comment by Oppila-Microsystems** [comment]
> In response to your queries on gitter: The conflicting file has been changed by a couple of pull requests for example #1286 and #1343 since the point in time when you created your branch. You will need to rebase your PR branch on top of the current version of branch develop locally and resolve the conflict manually. Once you have finished that, force push your branch and this will make the error go away.
> 
> I also see in your PR that you are adding many new tests. Of those, we only need the following three:
> 
> ```
> platform-specific/oppila/orouter/client/oppila:BOARD=orouter \
> platform-specific/oppila/orouter/ip64-router/oppila:BOARD=orouter \
> platform-specific/oppila/oppila \
> ```
> 
> You don't need to add tests to the out-of-tree build.
> 
> If you are going to rebase the PR to fix this error, I strongly suggest cleaning up your history. Commit messages are not in a good shape at the moment.
> 
> This is a good example of what a good platform-adding PR could look like: #1310
> 
> Is this a commercially-available product? If the PR gets merged, will you be looking after the port in the longer term?
> 
> We will also need a wiki documentation page, but this can wait till the PR is in a good shape.
> 
> Thanks!

thank you so much for reviewing and thanks for the support.

**Comment by Oppila-Microsystems** [comment]
> > In response to your queries on gitter: The conflicting file has been changed by a couple of pull requests for example #1286 and #1343 since the point in time when you created your branch. You will need to rebase your PR branch on top of the current version of branch develop locally and resolve the conflict manually. Once you have finished that, force push your branch and this will make the error go away.
> > I also see in your PR that you are adding many new tests. Of those, we only need the following three:
> > ```
> > platform-specific/oppila/orouter/client/oppila:BOARD=orouter \
> > platform-specific/oppila/orouter/ip64-router/oppila:BOARD=orouter \
> > platform-specific/oppila/oppila \
> > ```
> > 
> > 
> > You don't need to add tests to the out-of-tree build.
> > If you are going to rebase the PR to fix this error, I strongly suggest cleaning up your history. Commit messages are not in a good shape at the moment.
> > This is a good example of what a good platform-adding PR could look like: #1310
> > Is this a commercially-available product? If the PR gets merged, will you be looking after the port in the longer term?
> > We will also need a wiki documentation page, but this can wait till the PR is in a good shape.
> > Thanks!
> 
> thank you so much for reviewing and thanks for the support.

product is available and wiki page is under construction.

**Comment by Oppila-Microsystems** [comment]
> > > In response to your queries on gitter: The conflicting file has been changed by a couple of pull requests for example #1286 and #1343 since the point in time when you created your branch. You will need to rebase your PR branch on top of the current version of branch develop locally and resolve the conflict manually. Once you have finished that, force push your branch and this will make the error go away.
> > > I also see in your PR that you are adding many new tests. Of those, we only need the following three:
> > > ```
> > > platform-specific/oppila/orouter/client/oppila:BOARD=orouter \
> > > platform-specific/oppila/orouter/ip64-router/oppila:BOARD=orouter \
> > > platform-specific/oppila/oppila \
> > > ```
> > > 
> > > 
> > > You don't need to add tests to the out-of-tree build.
> > > If you are going to rebase the PR to fix this error, I strongly suggest cleaning up your history. Commit messages are not in a good shape at the moment.
> > > This is a good example of what a good platform-adding PR could look like: #1310
> > > Is this a commercially-available product? If the PR gets merged, will you be looking after the port in the longer term?
> > > We will also need a wiki documentation page, but this can wait till the PR is in a good shape.
> > > Thanks!
> > 
> > 
> > thank you so much for reviewing and thanks for the support.
> 
> product is available and wiki page is under construction.

can i close this pull request and do it from the beginning

**Comment by g-oikonomou** [comment]
> can i close this pull request and do it from the beginning

I would advise not. Just keep updating the same branch on your repo and this pull request will reflect your changes. If you close this we will end up having all the conversation history in two difference places

**Comment by Oppila-Microsystems** [comment]
> > can i close this pull request and do it from the beginning
> 
> I would advise not. Just keep updating the same branch on your repo and this pull request will reflect your changes. If you close this we will end up having all the conversation history in two difference places

**Comment by Oppila-Microsystems** [comment]
> > > can i close this pull request and do it from the beginning
> > 
> > 
> > I would advise not. Just keep updating the same branch on your repo and this pull request will reflect your changes. If you close this we will end up having all the conversation history in two difference places

okay

**Comment by Oppila-Microsystems** [comment]
> > can i close this pull request and do it from the beginning
> 
> I would advise not. Just keep updating the same branch on your repo and this pull request will reflect your changes. If you close this we will end up having all the conversation history in two difference places

i have done with updation. could you please check out and tell me if i have to do any changes

**Comment by alexstanoev** [comment]
To fix the documentation warnings:
```
/home/user/contiki-ng/arch/platform/oppila/dev/adc-omote.h:36: warning: missing title after \defgroup oppila-adc-interface
/home/user/contiki-ng/arch/platform/oppila/dev/omote-sensors.h:36: warning: missing title after \defgroup oppila-sensors
```
You need to add a title after `\defgroup` - your `arch/platform/oppila/dev/adc-sensors.h` file for example does it correctly.

**Comment by Oppila-Microsystems** [comment]
> To fix the documentation warnings:
> 
> ```
> /home/user/contiki-ng/arch/platform/oppila/dev/adc-omote.h:36: warning: missing title after \defgroup oppila-adc-interface
> /home/user/contiki-ng/arch/platform/oppila/dev/omote-sensors.h:36: warning: missing title after \defgroup oppila-sensors
> ```
> 
> You need to add a title after `\defgroup` - your `arch/platform/oppila/dev/adc-sensors.h` file for example does it correctly.

yes i have added tittle to those dev files. could you please check and let me know the further changes if any

**Comment by Oppila-Microsystems** [comment]
> To fix the documentation warnings:
> 
> ```
> /home/user/contiki-ng/arch/platform/oppila/dev/adc-omote.h:36: warning: missing title after \defgroup oppila-adc-interface
> /home/user/contiki-ng/arch/platform/oppila/dev/omote-sensors.h:36: warning: missing title after \defgroup oppila-sensors
> ```
> 
> You need to add a title after `\defgroup` - your `arch/platform/oppila/dev/adc-sensors.h` file for example does it correctly.

can you please check and tell me further changes if any

**Comment by atiselsts** [comment]
The CI checks now pass. Please squash the many commits in a single or a few commit messages, as George recommended. You can do that by:

    git remote add contiki-orig https://github.com/contiki-ng/contiki-ng.git
    git remote update
    git rebase -i contiki-orig/develop
    git push -f origin

**Pull request closed without merging**
