### PR TITLE
rpl-udp example: remove uipbuf tuning of MAC retries

### PR DESCRIPTION
**Pull request by simonduq**
I believe the `uipbuf_set_attr` example did cause confusion, by sending some unreliable packets. When not ACKed at MAC, can have bad consequences on link estimates, as ETX will be updated with `ETX_NOACK_PENALTY`. Also, the example is intended as a minimal RPL UDP example and seems to be the starting point to many users, so I think this is not the ideal place to document `uipbuf_set_attr`.

### CODE REVIEW

**Comment by atiselsts** [comment]
How about moving this API demonstration to another example this, then?

I see the problem with `ETX_NOACK_PENALTY`, but to be honest, it sounds like a bug, an unforeseen consequence we should have noticed when the transmission attribute was introduced.
It would be more logical to use `transmissions + X` as the transmission count for ETX when no ack is received instead of a fixed `ETX_NOACK_PENALTY`.

**Comment by simonduq** [comment]
Agree with everything. Sorry for a PR that was not very constructive ;)
BTW what would be nice for such API is to have it documented on the wiki as well.

**Comment by simonduq** [comment]
Done :)

**Comment by atiselsts** [comment]
OK, I see, since `MAX_FRAME_RETRIES` is 7 both for TSCH and CSMA, the new value `12`  for `ETX_NOACK_PENALTY` keeps the old behavior exactly.
Nice to have one more example! I checked that it builds on all platforms.

**Comment by simonduq** [comment]
Right, and I should add a text for at least one platform!

**Comment by simonduq** [comment]
Test added (on Zoul)

**Pull request merged**
