### PR TITLE
Merge master back into develop

### PR DESCRIPTION
**Pull request by g-oikonomou**
Merge master back into develop

### CODE REVIEW

**Comment by simonduq** [comment]
Warning here: do not press "update branch", but rather do a forced merge.

Updating the branch would result in a commit to master (the source branch)

**Comment by g-oikonomou** [comment]
I wonder whether we should be using an intermediate branch here in the future, just to make sure any accidental merges don't mess around with master

**Comment by simonduq** [comment]
I think we should yes!

**Comment by simonduq** [comment]
But we should still not do "upgrade branch" even on that one, so what we get is still a clean master-to-develop merge

**Comment by g-oikonomou** [comment]
Yeah. But if someone does so accidentally, we won't mess master and a simple force-push to the branch in question will fix

**Pull request merged**
