### PR TITLE
docker: fix an issue on net.ipv6.conf.all.disable_ipv6

### PR DESCRIPTION
**Pull request by yatch**
# Issue
We currently try to change `net.ipv6.conf.all.disable_ipv6` to `0` by `.profile`, but it doesn't work.

```
$ docker run -ti contiker/contiki-ng
sysctl: setting key "net.ipv6.conf.all.disable_ipv6": Read-only file system
user@57f569a70c56:~/contiki-ng$
```

Here is another example:
```
$ docker run -ti contiker/contiki-ng sysctl net.ipv6.conf.all.disable_ipv6
net.ipv6.conf.all.disable_ipv6 = 1
```

# Solution

As per [the official documentation of Docker](https://docs.docker.com/engine/reference/commandline/run/), `--sysctl` should be passed to `docker run` for this purpose:

> The --sysctl sets namespaced kernel parameters (sysctls) in the container. For example, to turn on IP forwarding in the containers network namespace, run this command:

# What does this PR do?

This PR proposes to remove the `sysctl` command from `.profile`. The Wiki page will be updated accordingly, adding `--sysctl net.ipv6.conf.all.disable_ipv6=0` to `contiker` aliases.

# Demo

```
$ docker run --sysctl net.ipv6.conf.all.disable_ipv6=0 -ti contiker/contiki-ng sysctl net.ipv6.conf.all.disable_ipv6
net.ipv6.conf.all.disable_ipv6 = 0
```

# Version Info

```
$ docker image ls | grep contiki-ng
contiker/contiki-ng    latest              8307892c9c77        9 months ago        3.32GB

$ docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:18:17 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:17:52 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

This issue is confirmed on Docker for Windows as well.

### CODE REVIEW

**Comment by yatch** [comment]
Seems the `sysctl` command line in `.profile` is effective in the docker environment on Travis... Removing the command caused test failures. I add `before_script` section in `.travis.yml` so as to enable IPv6 in containers for testing.

**Comment by yatch** [comment]
Hmm... The test failed because of this...
```
opened tun device ``/dev/tun0''
SIOCSIFADDR: Permission denied
```
I got green on my Travis account, though... https://travis-ci.org/yatch/contiki-ng/builds/569843872

**Comment by jeppenodgaard** [comment]
> 
> 
> Hmm... The test failed because of this...
> 
> ```
> opened tun device ``/dev/tun0''
> SIOCSIFADDR: Permission denied
> ```
> 
> I got green on my Travis account, though... https://travis-ci.org/yatch/contiki-ng/builds/569843872

I've seen that error before. Adding these options might fix it:
-v "/dev/:/dev/" --cap-add NET_ADMIN --net=host

**Comment by g-oikonomou** [comment]
I'm note sure when / why this started happening, nor whether this is a proper way of fixing this. But I can confirm the bug; it is quite disruptive and we need to fix it somehow

**Comment by simonduq** [comment]
IPv6 and tun in Docker is always difficult. Running with full privileges should work (as we do now in Travis), but has downsides obviously. 

I don't think we can solve this in `before_script`, as this will run outside of the container.

What worked for me before, when trying to avoid `--privileged`, was: `--cap-add=NET_ADMIN --device=/dev/net/tun --sysctl net.ipv6.conf.all.disable_ipv6=0`. Net-admin required for both Tun and IPv6, and the specific tun dev also needs giving explicit access

**Comment by simonduq** [comment]
@yatch ?

**Comment by yatch** [comment]
I'll be back to this next week, hopefully Monday.

**Comment by g-oikonomou** [comment]
Changed base to branch `release-4.4`. Rebase possibly required.

**Comment by yatch** [comment]
This PR is ready. But, the test failed because of Issue #1084. So, this PR depends on PR #1085.

**Comment by yatch** [comment]
FYI: `contiker` alias definitions in the wiki page have been updated: https://github.com/contiki-ng/contiki-ng/wiki/Docker/_history

**Comment by g-oikonomou** [comment]
This is going to be the next one to merge. Is it ready?

**Pull request merged**
