### PR TITLE
Rename srf06-cc26xx to cc26x0-cc13x0

### LINKED ISSUE #83: Fix the confusing name srf06-cc26xx
At least I am confused, as this also contains cc13xx. 
Any way to make things clearer? And easier to type?

### PR DESCRIPTION
**Pull request by yatch**
This PR aims to reduce confusion over the platform name of `srf06-cc26xx`. Under `arch/platform/srf06-cc26xx`,  we have sub-platforms other than `srf06/cc26xx` such as `launchpad/cc1310` and `sensortag/cc2650`.

The proposal is renaming it to `arch/platform/cc26x0-cc13x0`. And, additional modification are made accordingly.

The commits here will be squashed into one later.

Closes #83

### CODE REVIEW

**Comment by fontikos** [comment]
Just fyi, Texas Instruments has announced new chips `cc2652` and `cc1352`. Not sure if it makes sense to be proactive.

https://e2e.ti.com/support/wireless_connectivity/bluetooth_low_energy/f/538/t/657842

**Comment by yatch** [comment]
@fontikos Thank you for the information! I'm aware of them; yes, `cc26xx-cc13xx` having under `arch/platform` as well is another option.

**Comment by g-oikonomou** [comment]
I am near 100% certain that cc13x2 / cc26x2 will be a totally different platform with major design differences (to start with, at least). Therefore I propose x0

**Comment by yatch** [comment]
Yes! Let me try it.

**Comment by yatch** [comment]
I re-did the renaming on the latest `develop` branch. It seems `arch/cpu/cc26xx-cc13xx/` can be renamed to `arch/cpu/cc26x0-cc13x0/` as well. I'll do this by the end of today.

**Comment by yatch** [comment]
It's ready for review :-) Not only `arch/platform/srf06-cc26xx` but also `arch/cpu/cc26xx-cc13xx/` are renamed.

**Comment by g-oikonomou** [comment]
Thanks. Will review asap

**Comment by g-oikonomou** [comment]
So

We need to resolve remaining conflicts and merge this as a matter of priority before more conflicts get generated.

**Pull request merged**
