### PR TITLE
update script for building msp430 from source

### PR DESCRIPTION
**Pull request by jbrusey**
Revised PR for updating the script for building msp430 from source. This revised PR only includes the script and reference to it in the toolchain documentation.

### CODE REVIEW

**Comment by jbrusey** [comment]
@pjonsson just to let you know that I have revised the PR as suggested. I couldn't quite work out how to do it in the same pr so submitted another one.

**Comment by pjonsson** [comment]
@jbrusey I got the following error inside the docker when trying to run the script:

```
patching file gas/doc/c-arc.texi
Hunk #1 succeeded at 220 with fuzz 2 (offset 8 lines).
patching file gas/doc/c-arm.texi
Hunk #1 succeeded at 380 (offset 4 lines).
Hunk #2 succeeded at 441 (offset 8 lines).
Hunk #3 succeeded at 485 (offset 10 lines).
patching file gas/doc/c-cr16.texi
Hunk #1 FAILED at 43.
1 out of 1 hunk FAILED -- saving rejects to file gas/doc/c-cr16.texi.rej
patching file gas/doc/c-mips.texi
Hunk #1 succeeded at 234 (offset 14 lines).
patching file gas/doc/c-score.texi
Hunk #1 succeeded at 37 with fuzz 1 (offset 1 line).
Hunk #2 succeeded at 49 (offset 1 line).
patching file gas/doc/c-tic54x.texi
Hunk #1 FAILED at 108.
Hunk #2 succeeded at 126 with fuzz 2 (offset 1 line).
Hunk #3 succeeded at 309 (offset 1 line).
Hunk #4 succeeded at 345 with fuzz 1 (offset 1 line).
1 out of 4 hunks FAILED -- saving rejects to file gas/doc/c-tic54x.texi.rej
Build failed - /tmp/tmp.bKfnrrU2Ny not removed
```
Looking at the rejects:
```
$ cat /tmp/tmp.bKfnrrU2Ny/binutils-2.22/gas/doc/c-tic54x.texi.rej
--- gas/doc/c-tic54x.texi
+++ gas/doc/c-tic54x.texi
@@ -108,7 +108,7 @@ In this example, x is replaced with SYM2; SYM2 is replaced with SYM1, and SYM1
 is replaced with x.  At this point, x has already been encountered
 and the substitution stops.
 
-@smallexample @code
+@smallexample
  .asg   "x",SYM1
  .asg   "SYM1",SYM2
  .asg   "SYM2",x
$ /tmp/tmp.bKfnrrU2Ny/binutils-2.22/gas/doc/c-cr16.texi.rej 
--- gas/doc/c-cr16.texi
+++ gas/doc/c-cr16.texi
@@ -43,26 +43,33 @@ Operand expression type qualifier is an optional field in the instruction operan
 CR16 target operand qualifiers and its size (in bits):
 
 @table @samp
-@item Immediate Operand
-- s ---- 4 bits
-@item
-- m ---- 16 bits, for movb and movw instructions.
-@item
<more lines>
```
If it is hard to fix those things, I think we could make the old binutils build with the workaround:
```
make MAKEINFO=true CFLAGS="-Wno-error"
make MAKEINFO=true install
```

Using that workaround, the Contiki-NG tests pass with the built compiler for me.

**Comment by pjonsson** [comment]
@jbrusey the force push seemed to work, did you close this by accident?

**Comment by jbrusey** [comment]
@pjonsson Not sure what caused the PR to close. I had to reset to clean up and perhaps having no commits caused a close automatically. I found the problem with the patch - I had accidentally stripped trailing blanks in places where they were required for a match. Apologies for this oversight!

**Review by pjonsson — APPROVED** [review]

**Comment by pjonsson** [comment]
All regression tests pass with a compiler built by the script inside the container.

@jbrusey sorry for the delay, been working on non-Contiki-NG-related projects after Christmas so I'm slowly working through my backlog now.

**Review by nfi — APPROVED** [review]

**Comment by simonduq** [comment]
Hi!

This was my mistake, very sorry about it, re-opening this PR now.

What happened is the following: I was switching the base branch for this repository https://github.com/wittra/contiki-ng from develop to wittra. But accidentally, I made the change on the wrong repo (this repo) and instead of switching the base branch I renamed it. And somehow github deleted develop and closed all PRs...

Many apologies for this mishap 🙏; I haven't contributed in a while.. but now at least everybody got some notification from me :p

**Pull request merged**
