### PR TITLE
Added check for block offset overflow in CoAP block2 requests.

### PR DESCRIPTION
**Pull request by nfi**
The block offset is stored in a signed variable in calls to CoAP handlers and too large block offsets will overflow into negative values.

The fixes the issue reported in #425.

### CODE REVIEW

**Comment by g-oikonomou** [comment]
@nfi Should we include this in the upcoming release?

Also, I did not look at this in detail, but I was getting the impression when I looked at #425 that this might have been caused by packets with unknown option values, was I mistaken?

**Comment by simonduq** [comment]
+1 on including in 4.1!
@nfi does this fix all the issues in #425 ?

**Comment by nfi** [comment]
@g-oikonomou I would vote for including it in 4.1 also. It is possible to reproduce this issue using only known legal option values together with a CoAP resource that does not validate the block offset such as the example plugfest large-update resource.

@simonduq It fixes the crash described in #425. But testing with #425 also showed that the current CoAP implementation is too forgiving when parsing CoAP headers. Several options in #425 should make CoAP simply respond with Bad Request without processing the payload.

**Comment by nfi** [comment]
To clarify: the issue is that the example CoAP resource plugfest large-update does not check the block offset. If all block2 capable CoAP resources would check the offset instead of simply trusting it, this would not be an issue.

Adding a check in CoAP engine as done in this PR will make sure it will not be an issue even if a CoAP resource does not check the block offset but also adds a limit of the max block offset. Perhaps a better approach would be to update the example CoAP resources after all and document that all block2 capable CoAP resources need to check this. What do you think?

For the long term, I think changing the CoAP handler API to not use signed variables would completely remove the issue.

**Comment by joakimeriksson** [comment]
From what it looks in the RFC it is not a significant limitation to cut down to 31 bits.

**Pull request merged**
