### PR TITLE
Extend the logging module to support custom module prefix

### PR DESCRIPTION
**Pull request by nfi**
Adds a configuration option `LOG_CONF_OUTPUT_PREFIX` to specify a custom output function to output the log level and module name in the beginning of each log line. This makes it possible to add a timestamp or use a different log module prefix format than the default.

### CODE REVIEW

**Comment by simonduq** [comment]
Great! Question: will this play nicely in the `LOG_WITH_LOC` cases, which uses `LOG_OUTPUT` directly?

**Comment by nfi** [comment]
The module prefix is done before the LOC is generated so I do not think it will be any different from before. Here is an example with custom module prefix and LOC enabled:

```
2017-11-30 20:00:12.981 [coap-ipv4] DBG  - [coap-ipv4.c: 259] parsing endpoint coap://127.0.0.1 => endpoint at 127.0.0.1:5683
2017-11-30 20:00:12.981 [coap-ipv4] INFO - [coap-ipv4.c: 426] CoAP server listening on port 5683
```

But perhaps we should make also the LOC format configurable in the same way as the module prefix by adding  `LOG_CONF_OUTPUT_LOC(file, line)` which defaults to use `LOG_OUTPUT` as today?

**Comment by simonduq** [comment]
I'm mostly concerned about the fact that `LOG_CONF_OUTPUT_PREFIX` might choose not to even rely on `LOG_OUTPUT` at all, while `LOG_WITH_LOC` is always `LOG_OUTPUT`-based.

Could either add `LOG_CONF_OUTPUT_LOC` as you suggest, or make sure `LOG_CONF_OUTPUT_PREFIX` always calls `LOG_OUTPUT` (but defines its own printf format)

**Comment by nfi** [comment]
The log data also rely on `LOG_OUTPUT` so regardless of `LOG_WITH_LOC`, things will be strange if `LOG_CONF_OUTPUT_PREFIX` would not be based on `LOG_OUTPUT`. I simply assumed that any implementation of `LOG_CONF_OUTPUT_PREFIX` would be based on `LOG_OUTPUT`  like the rest of the log functions.

**Comment by simonduq** [comment]
Yes right now I'm with you. Was somehow assuming one of the goals was to have `LOG_CONF_OUTPUT_PREFIX` possibly bypass `LOG_OUTPUT`.

Works for me. Is this ready for merging?

**Comment by nfi** [comment]
Should I add `LOG_CONF_OUTPUT_LOC` also?

**Comment by simonduq** [comment]
I'd say this is overkill. Maybe as a comment to `LOG_CONF_OUTPUT_PREFIX` say the def is expected to use `LOG_OUTPUT`?

**Comment by nfi** [comment]
Ok, I added a comment that implementations of `LOG_CONF_OUTPUT_PREFIX` should be based on `LOG_OUTPUT`.

**Comment by simonduq** [comment]
Ah that is great :)

**Pull request merged**
