### PR TITLE
Proposal: setup and teardown functions for unit tests

### PR DESCRIPTION
**Pull request by kam193**
This is a proposal of extending unit test library. Setup and teardown functions can be defined to run before/after each test (to e.g. prepare/clean data), which is common pattern when writing unit tests.

### CODE REVIEW

**Comment by atiselsts** [comment]
I don't think we need this functionality. The PR itself does no provide any usage examples. I'd vote against unless it is better justified.

**Comment by kam193** [comment]
Right, I should add an example. I created it based on my experience when I used Contiki-NG UT toolkit. If you think it could be useful - I will add an example.

**Comment by nvt** [comment]
I agree with @atiselsts. The benefit of the introduced functionality should be shown either in this thread or in example code added to the PR.

**Comment by kam193** [comment]
Unfortunately, I've stopped working with Contiki some time ago. As so, I'm not planning to finish this in the near future.

**Pull request closed without merging**
